CREATE TABLE [dbo].[AddressOfCompany]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [INDEX] NCHAR(6) NOT NULL, 
    [CODE_REGION] NCHAR(3) NOT NULL, 
    [DISTRICT] NCHAR(30) NOT NULL, 
    [CITY] NCHAR(30) NULL, 
    [SETTLEMENT] NCHAR(30) NULL, 
    [STREET] NCHAR(30) NOT NULL, 
    [BUILD] NCHAR(5) NOT NULL, 
    [HOUSING] NCHAR(4) NULL, 
    [APARTMENT] NCHAR(3) NOT NULL, 
    [COMPANY_ID] INT NOT NULL
    CONSTRAINT [FK_AddressOfCompany_Company] FOREIGN KEY ([COMPANY_ID]) REFERENCES [COMPANY]([ID]),
    UNIQUE(COMPANY_ID)
)
