CREATE TABLE [dbo].[ADDRESS]
(
	[UID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [INDEX] INT NOT NULL, 
    [CODE_REGION] SMALLINT NOT NULL, 
    [DISTRICT] NVARCHAR(30) NOT NULL, 
    [CITY] NVARCHAR(30) NULL, 
    [SETTLEMENT] NVARCHAR(30) NULL, 
    [STREET] NVARCHAR(30) NOT NULL, 
    [BUILD] NVARCHAR(5) NOT NULL, 
    [HOUSING] NVARCHAR(4) NULL, 
    [APARTMENT] SMALLINT NOT NULL, 
    [COMPANY_UID] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT [FK_Address_Company] FOREIGN KEY ([COMPANY_UID]) REFERENCES [COMPANY]([UID]),
    UNIQUE(COMPANY_UID)
)
