CREATE TABLE [dbo].[Authority]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [START] DATE NOT NULL, 
    [END] DATE NOT NULL, 
    [NUMBER] NCHAR(30) NOT NULL, 
    [COMPANY_ID] INT NOT NULL,
    CONSTRAINT [FK_Authority_Company] FOREIGN KEY ([COMPANY_ID]) REFERENCES [COMPANY]([ID]) ON DELETE CASCADE,
    UNIQUE(COMPANY_ID)
)
