CREATE TABLE [dbo].[COMPANY]
(
	[UID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [NAME] NVARCHAR(40) NOT NULL, 
    [KPP] NVARCHAR(12) NOT NULL, 
    [INN] NVARCHAR(9) NOT NULL, 
    [CLIENT_BASE_ON] NVARCHAR(10) NOT NULL,
    [DIRECTOR_UID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_Company_Person] FOREIGN KEY ([DIRECTOR_UID]) REFERENCES [PERSON]([UID]),
    UNIQUE([DIRECTOR_UID])
)
