CREATE TABLE [dbo].[MANAGER]
(
	[UID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(),
    [FIRST_NAME] NVARCHAR(20) NOT NULL, 
    [LAST_NAME] NVARCHAR(20) NOT NULL ,
    [MIDDLE_NAME] NVARCHAR(20) NULL, 
    [PHONE] NVARCHAR(11) NOT NULL
)
