CREATE TABLE [dbo].[MANAGER]
(
	[UID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FIRST_NAME] NCHAR(20) NOT NULL, 
    [LAST_NAME] NCHAR(20) NOT NULL, 
    [MIDDLE_NAME] NCHAR(20) NULL, 
    [PHONE] NCHAR(11) NOT NULL
)
