CREATE TABLE [dbo].[PASSPORT]
(
	[UID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [SERIES] NCHAR(4) NOT NULL, 
    [NUMBER] NCHAR(6) NOT NULL, 
    [DATE_ISSUE] DATE NOT NULL, 
    [PLACE_ISSUE] NCHAR(100) NOT NULL, 
    [MANAGER_UID] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Passport_Manager] FOREIGN KEY ([MANAGER_UID]) REFERENCES [Manager]([UID]) on delete CASCADE,
    UNIQUE(MANAGER_UID)
)
