CREATE TABLE [dbo].[PERSON]
(
	[UID]UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FIRST_NAME] NCHAR(30) NOT NULL, 
    [LAST_NAME] NCHAR(30) NOT NULL, 
    [MIDDLE_NAME] NCHAR(30) NULL, 
    [COMPANY_UID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_Person_Company] FOREIGN KEY ([COMPANY_UID]) REFERENCES [COMPANY]([UID]) ON DELETE CASCADE,
    UNIQUE([COMPANY_UID])
)
